### ISSUE TITLE
Add commonXsltExtensionSupport.xsl with dita.xsl.html5 extension point

### ISSUE THREAD

**Issue by jelovirt** [dita-community/org.dita-community.common.xslt#20]
The stylesheet `commonXsltExtensionSupport.xsl` is added using `dita.xsl.xhtml` extension point. For DITA-OT 2.4 also the HTML5 should have this import using extension point `dita.xsl.html5`.

**Comment by raducoravu** [comment]
@drmacro This seems to be fixed in the latest release, right?

**Comment by drmacro** [comment]
Yes, this is reflected in the latest code. Closing as fixed.
