### ISSUE TITLE
Extra warning with Saxon 9.9

### ISSUE THREAD

**Issue by raducoravu** [dita-community/org.dita-community.common.xslt#22]
[pipeline] Warning at function df:mapIsChunkToContent on line 887 of dita-support-lib.xsl:
 [pipeline]   SXWN9000: A function that computes atomic values should use xsl:sequence rather than xsl:value-of

**Comment by drmacro** [comment]
This has been corrected. Not sure when, but curren tcode uses xsl:sequence
